version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fit-note-mongodb
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    command: mongod --bind_ip_all --auth
    volumes:
      - mongodb_data:/data/db
    network_mode: "host"
    restart: always
    security_opt:
      - no-new-privileges:true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fit-note-app
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://localhost:27017/fit-note
      - MONGODB_USER=admin
      - MONGODB_PASS=password123
      - MONGODB_AUTH_SOURCE=admin
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb
    networks:
      - fit-note-network
    restart: always

volumes:
  mongodb_data:
    name: fit-note-mongodb-data

networks:
  fit-note-network:
    name: fit-note-network
