version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fit-note-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - fit-note-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fit-note-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password123
    depends_on:
      - mongodb
    networks:
      - fit-note-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fit-note-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fit-note-network
    restart: always

volumes:
  mongodb_data:
    name: fit-note-mongodb-data

networks:
  fit-note-network:
    name: fit-note-network
