version: '3.8'

services:
  frontend:
    container_name: fit-note-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - frontend_dist:/app/frontend/dist
    command: tail -f /dev/null # 保持容器运行
    networks:
      - app-network

  nginx:
    container_name: fit-note-nginx
    build:
      context: .
      dockerfile: frontend/nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

  backend:
    container_name: fit-note-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/fit-note
      - MONGODB_USER=admin
      - MONGODB_PASS=password123
      - MONGODB_AUTH_SOURCE=admin
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: fit-note-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    command: mongod --bind_ip_all --auth
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always
    security_opt:
      - no-new-privileges:true

volumes:
  mongodb_data:
    name: fit-note-mongodb-data
  frontend_dist:
    name: fit-note-frontend-dist

networks:
  app-network:
    driver: bridge
